# version: "3.9"
services:
  ollama_cpu:
    image: ollama/ollama
    container_name: ollama_cpu
    ports:
      - "11435:11434"
    volumes:
      - ollama:/root/.ollama
    stdin_open: true  # позволяет использовать docker exec -it
    tty: true         # добавляет поддержку для интерактивного tty
    
volumes:
  ollama:
    driver: local
